### ISSUE TITLE
kubelet is assigning port number to hostname instead of local host

### ISSUE THREAD

**Issue by belwalkar** [cni-genie/CNI-Genie#145]
Because of this CNIgene can not connect and kube-dns container dosent come up
curl http://127.0.0.1:4194/metrics
curl: (7) Failed to connect to 127.0.0.1 port 4194: Connection refused

root@k8s-01:~# netstat -ulpt | grep 4194
tcp        0      0 k8s-01:4194             *:*                     LISTEN      2251/kubelet  

@sushanthakumar  is there any work around for this Gopinath Tagat worked with you on

**Comment by belwalkar** [comment]
Events:
  Type     Reason                  Age                    From             Message
  ----     ------                  ----                   ----             -------
  Normal   SandboxChanged          15m (x23691 over 19h)  kubelet, k8s-01  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  5m (x23899 over 19h)   kubelet, k8s-01  Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "kube-dns-7bd4d5fbb6-hnr6j_kube-system" network: CNI Genie Add IP internal error: CNI Genie error at ParsePodAnnotations: CNI Genie failed to retrieve CNS list from cAdvisor = unable to get "get all containers info" from "http://127.0.0.1:4194/api/v1.3/containers": Post http://127.0.0.1:4194/api/v1.3/containers: dial tcp 127.0.0.1:4194: connect: connection refused, result: %!!(MISSING)s(<nil>)

**Comment by sushanthakumar** [comment]
@belwalkar , Surely we would like to help you out with your use case
Below is the issue, Gopinath has raised and genie's default plugin feature can be used to resolve it
https://github.com/Huawei-PaaS/CNI-Genie/issues/98

If you plan to make use of No annotation and use default plugin, from above logs, it looks like your genie conf  does not have this configuration. Below link might help  you to know how to use it
https://github.com/Huawei-PaaS/CNI-Genie/blob/master/docs/default-plugin/README.md

In case, if it can not solve your scenario, we can discuss further to fit it
you can join our slack channel for better communication, 
https://cni-genie.slack.com

**Comment by belwalkar** [comment]
Thanks Sushsnt for your response. I need a invite to creeate account for this slack org.

**Comment by belwalkar** [comment]
Sorry for being not clear. I gave gopi's reference as he pointed out me to this. but it seems like its entirely different issue. Not related what Gopi was trying to resolve. Thanks

**Comment by belwalkar** [comment]
Hi @sushanthakumar, here is the genie config I have: 

```
{
    "name": "k8s-pod-network",
    "type": "genie",
    "log_level": "info",
    "datastore_type": "kubernetes",
    "hostname": "k8s-01",
    "default_plugin": "calico",
    "policy": {
        "type": "k8s",
        "k8s_auth_token": "xxxxxxxxxxxxxxxxxxxxxxxxx"
    },
    "kubernetes": {
        "k8s_api_root": "https://10.233.0.1:443",
        "kubeconfig": "/etc/cni/net.d/genie-kubeconfig"
    },
    "romana_root": "http://:",
    "segment_label_name": "romanaSegment"
}
```

The config does look OK to me. 

The trouble is CNI Genie is looking for the CAdvisor port on `127.0.0.1` while it should really be looking at `k8s-01` which is the host name on which the CNI Genie is running. This is because it looks like the kubelet is binding the CAdvisor port to the host name specifically and not to `0.0.0.0`.

**Comment by sushanthakumar** [comment]
@belwalkar , cadvisor will come into picture when genie wants to trigger smart selection feature ie user does not wish to give plugin and mentions cni : " " in pod yaml. When this is selected, by default genie tries to contact cadvisor to get network usage info of different plugins with address "http://127.0.0.1:4194" and expects that cadvisor is reachable at that link

However genie supports user defined cadvisor link. We can add below line in genie.con file
"cAdvisor_address": "http://k8s-01:5050",
which means user has started cadvisor at above link
so u can add above line with your hostname and portnumber and genie will select one of the plugins and give you
You can refer below PR link about this
https://github.com/Huawei-PaaS/CNI-Genie/pull/126/

Hope this can solve your scenario. Feel free to contact us if any issues/doubts
meanwhile you can provide your email id to be included in slack so that I can send u invite 
We can use it for faster/better communication in feature

**Comment by belwalkar** [comment]
my email id is dumbbel@gmail.com

**Comment by belwalkar** [comment]
I tried this but didnt work. do I need to add some patch?

**Comment by sushanthakumar** [comment]
Oho really. Not an issue, I have invited you to slack, we can directly communicate and look into this case

**Comment by m1093782566** [comment]
@belwalkar You can also raise a PR for what you need.

**Comment by belwalkar** [comment]
Thanks for slack invite.
